### ISSUE TITLE
mod request Iguana tweaks 

### ISSUE THREAD

**Issue by Mementh** [legracen/Chaos-Portal-Pack#12]
Iguana tweaks considered for options with tinkers construct to make weapons etc upgradeable over 

time.. IE make it and replace parts over time

also gives more upgrade options and makes it so you get "used" to using something..

**Comment by Mementh** [comment]
this mod lets you make a sword for example at the start out of stone!

as you get more metals you replace parts one at a time.

this makes the sword better over time.

also it makes it so that you can't jump ahead you have to kill things with it to make it better.

**Comment by legracen** [comment]
Not Being looked into at this time.
