### ISSUE TITLE
skystone crafting

### ISSUE THREAD

**Issue by Mementh** [legracen/Chaos-Portal-Pack#3]
currently there is a bee for this?!?!

but we talked about it using a crystal ground up.. and 4x or so cobble? if its a ender IO recipie add a diamond nugget?

**Comment by legracen** [comment]
test recapie in place to see if i have the alloy smelter recapie style correct. should be 2 certus dust 1 coal dust and 1 silicon as a test only. will alter more if that works to make it more expensive.

**Comment by legracen** [comment]
Temporary alloy smelter added to test if i have the coding style correct.

2 certus dust, 1 coal dust, 1 silicon

**Comment by legracen** [comment]
Current recipe is not working will try again tonight

**Comment by legracen** [comment]
Alloy smelter recapie now installed.

1 4x compressed cobblestone, 1 amber, 1 certus quartz dust in alloy smelter yeilds 4x skystone
