### ISSUE TITLE
agricraft needs fertile soil to be added to allow the cropsticks to work

### ISSUE THREAD

**Issue by Mementh** [legracen/Chaos-Portal-Pack#32]
There's also the ability to edit your configs to have other soils be used to grow things on. For example, if you edit your SoilWhitelist.txt file to include, say, this line: 
RandomThings:fertilizedDirt ( replace with fertalized soil and other soils from other mods)

**Comment by Mementh** [comment]
this would let me use other farm soil then the default and allow quicker growing? or at least non trampable deals

**Comment by legracen** [comment]
done
