### ISSUE TITLE
possible recipie for skystone

### ISSUE THREAD

**Issue by Mementh** [legracen/Chaos-Portal-Pack#46]
this makes a skystone dust using glowstone and obsidian and a diamond and allows you to smelt that to the ore.

furnace.addRecipe(<appliedenergistics2:tile.BlockSkyStone>, <appliedenergistics2:item.ItemMultiMaterial:45>);
mods.thermalexpansion.Furnace.addRecipe(16000, <appliedenergistics2:item.ItemMultiMaterial:45>, <appliedenergistics2:tile.BlockSkyStone>);

recipes.addShaped(<appliedenergistics2:item.ItemMultiMaterial:45>, [[<ore:dustObsidian>, <ore:dustGlowstone>, <ore:dustObsidian>], [<ore:dustGlowstone>, <ore:dustDiamond>, <ore:dustGlowstone>], [<ore:dustObsidian>, <ore:dustGlowstone>, <ore:dustObsidian>]]);

**Comment by legracen** [comment]
Alloy smelter recapie already in looking to add it to the smeltery as well
