### ISSUE TITLE
Harvestcraft Apiary does not produce honey

### ISSUE THREAD

**Issue by Mementh** [legracen/Chaos-Portal-Pack#61]
from what i can see they don't make honey

**Comment by Alairthephoenix** [comment]
They're not supposed to. Harvestcraft apiaries are totally separate from Forestry/Gendustry apiaries. 

Furthermore, the work flow is totally different, and doesn't involve much in the way of output. 

As far as I know, the honey from Forestry bees can be used in Harvestcraft recipes. 

TLDR: it's working as intended.

**Comment by Mementh** [comment]
then honey from harvestcraft has no source option.. it probabbly is a bug with the mod itself
