### ISSUE TITLE
Request architect mod

### ISSUE THREAD

**Issue by Mementh** [legracen/Chaos-Portal-Pack#64]
https://mods.curse.com/mc-mods/minecraft/264874-architect

this mod allows you to build things from blueprints.

It also lets you "copy" as a text string and keep it when not on server.. or build something developed in private

**Comment by legracen** [comment]
Investigating. Due to time constraint this won't be in the next update. Perhaps the one after that.

**Comment by legracen** [comment]
Added 2.6
