### ISSUE TITLE
Better Storage Chests are Unmovable.

### ISSUE THREAD

**Issue by Alairthephoenix** [legracen/Chaos-Portal-Pack#66]
Put a Reinforced Iron Chest down, then went to break the block and move it (its empty!) and I can't. So far I've tried: Bronze Paxel (Mekanism Tools), Iron Hammer (Tinker's Construct), and a vanilla diamond pick (since the harvest level is diamond). None of these work, it will look like it will break, then it...doesn't. The tools take the durability hit every time you try though.

**Comment by legracen** [comment]
Chest Mover Mod was added.
