### ISSUE TITLE
Add OreDictionaryConverter

### ISSUE THREAD

**Issue by mrogaski** [legracen/Chaos-Portal-Pack#69]
It might be worth adding OreDictionaryConverter to convert all duplicate ore types to one.

https://minecraft.curseforge.com/projects/oredictionaryconverter

**Comment by Mementh** [comment]
there is a converter already in.. it can auto convert like the AIE server had.

**Comment by legracen** [comment]
Testing this for 2.6.1+

**Comment by legracen** [comment]
added in 2.6.1
