### ISSUE TITLE
Find a new food source for kitties!!!! ( actually addons issue)

### ISSUE THREAD

**Issue by Mementh** [legracen/Chaos-Portal-Pack#70]
I have 3 cats in my base.. and they are making hairballs OFTEN.. when its supposed to be rare/random!

i hope this has a setting to increase the drop rate :)

**Comment by legracen** [comment]
Still happening?

**Comment by legracen** [comment]
I can turn off the hairballs but not reduce them at all.

**Comment by Mementh** [comment]
that would work :)

**Comment by legracen** [comment]
Disabled this feature in 2.6.1
