### ISSUE TITLE
cooking for blockheads can't make salt or fresh water.

### ISSUE THREAD

**Issue by Mementh** [legracen/Chaos-Portal-Pack#79]
I checked on vanilla MC and added just harvestcraft and cooking for blockheads and the recipies work in cooking for blockheads there.

not sure what could be the cause of the problem? another mods interaction maybe?

I can try to look tonight on single player and test from there?

**Comment by Mementh** [comment]
ok this is specifically cooking with blockheads being out of date/not updated :/

**Comment by legracen** [comment]
Updating in patch 2.6.1
